version: 0.2
phases:
  build:
    commands:
      - aws cloudformation package --template-file template.yaml --s3-bucket msa-sam-repository --output-template-file packaged-template.yaml
  post_build:
    commands:
      - tail packaged-template.yaml
      - aws cloudformation deploy --template-file packaged-template.yaml --stack-name msa-stack-createItem --capabilities CAPABILITY_IAM --no-fail-on-empty-changeset --debug